export function dashboardHtml(nonce) {
  const safeNonce = String(nonce).replace(/[^a-zA-Z0-9_-]/g, "");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HexWitness</title>
  <style nonce="${safeNonce}">:root{color-scheme:dark;background:#090d12;color:#e8f0f2;font:15px system-ui}body{max-width:1180px;margin:0 auto;padding:32px}h1{color:#72f1b8}small,.muted{color:#8fa3ad}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.card{background:#111922;border:1px solid #263744;border-radius:12px;padding:16px}pre{white-space:pre-wrap;overflow-wrap:anywhere}button{background:#72f1b8;color:#09100d;border:0;border-radius:7px;padding:8px 12px;font-weight:700}input{background:#091018;color:#fff;border:1px solid #385064;padding:8px;border-radius:7px;width:min(520px,70vw)}a{color:#72d8f1}</style></head><body>
  <h1>HexWitness</h1><p class="muted">Local, read-only evidence observatory. Retrieval suggests. Exact records prove.</p>
  <div class="grid"><section class="card"><h2>Health</h2><pre id="health">Loading…</pre></section><section class="card"><h2>Investigations</h2><pre id="investigations">Loading…</pre></section><section class="card"><h2>Adapter readiness</h2><pre id="adapters">Loading…</pre></section></div>
  <section class="card" style="margin-top:14px"><h2>Discovery-only search</h2><input id="query" placeholder="function, protocol, failed approach…"><button id="search">Search</button><pre id="results">No query.</pre></section>
  <script nonce="${safeNonce}">const get=async p=>{const r=await fetch(p);if(!r.ok)throw Error(await r.text());return r.json()};const out=(id,v)=>document.getElementById(id).textContent=JSON.stringify(v,null,2);Promise.all([get('/v1/health').then(v=>out('health',v)),get('/v1/investigations/report').then(v=>out('investigations',v)),get('/v1/adapters/diagnostics').then(v=>out('adapters',v))]).catch(e=>out('health',{error:e.message}));document.getElementById('search').onclick=()=>{const q=document.getElementById('query').value;get('/v1/discover?q='+encodeURIComponent(q)).then(v=>out('results',v)).catch(e=>out('results',{error:e.message}))};</script></body></html>`;
}
